function tools = catalog()
%catalog Return canonical VAAYU FleetAnalytics tool definitions for MCP-style routing.
    arguments (Output)
        % Tool definitions with name, aliases, description, input schema, output schema, and normalized query type
        tools (1,:) struct
    end

tools = struct( ...
    'Name', { ...
        "analyze_engine", ...
        "predict_failure", ...
        "explain_engine", ...
        "check_fleet", ...
        "check_operational_clusters", ...
        "check_airborne_engines", ...
        "list_airborne_engines", ...
        "check_maintenance_engines", ...
        "list_maintenance_engines", ...
        "check_degrading_engines", ...
        "check_critical_engines", ...
        "check_early_failure_engines", ...
        "check_top_risk_engines", ...
        "check_highest_risk_engine"}, ...
    'Aliases', { ...
        ["check_engine", "engine_status"], ...
        strings(1, 0), ...
        strings(1, 0), ...
        ["fleet_status", "fleet_summary"], ...
        ["cluster_counts", "bucket_counts", "health_clusters"], ...
        ["airborne_count", "count_airborne"], ...
        ["airborne_engines", "show_airborne"], ...
        ["maintenance_count", "count_maintenance"], ...
        ["maintenance_engines", "engines_in_maintenance"], ...
        ["degrading_engines", "check_degrading"], ...
        ["critical_engines", "check_critical"], ...
        ["early_failure_engines", "check_early_failure"], ...
        ["top_risk", "risk_engines"], ...
        ["highest_risk", "riskiest_engine"]}, ...
    'Description', { ...
        "Check health, status, fault class, confidence, RUL, HI, and operating state for one engine.", ...
        "Check the RUL/failure horizon for one engine. Current implementation uses the same deterministic snapshot path as analyze_engine.", ...
        "Explain the current condition or anomaly for one engine. Current implementation uses the same deterministic snapshot path as analyze_engine.", ...
        "Get the fleet KPI summary from the current dashboard snapshot.", ...
        "Get counts for HEALTHY, DEGRADING, CRITICAL, EARLY FAILURE, MAINT, plus operating-state counts such as Airborne and Ground Idle.", ...
        "Count airborne engines and include other operating-state cluster counts.", ...
        "List airborne engines with risk, failure mode, RUL, and health indicator.", ...
        "Count engines in maintenance and include other operating-state cluster counts.", ...
        "List engines in maintenance with failure modes, RUL, and health indicator.", ...
        "List operational degrading engines from the current dashboard snapshot.", ...
        "List operational critical engines from the current dashboard snapshot.", ...
        "List operational early-failure engines from the current dashboard snapshot.", ...
        "List the top risk engines sorted by lowest health indicator, then RUL.", ...
        "Return the single highest-risk engine sorted by lowest health indicator, then RUL."}, ...
    'InputArguments', { ...
        engineInputSchema(), ...
        engineInputSchema(), ...
        engineInputSchema(), ...
        fleetInputSchema(), ...
        fleetInputSchema(), ...
        fleetInputSchema(), ...
        fleetInputSchema(), ...
        fleetInputSchema(), ...
        fleetInputSchema(), ...
        fleetInputSchema(), ...
        fleetInputSchema(), ...
        fleetInputSchema(), ...
        topRiskInputSchema(), ...
        fleetInputSchema()}, ...
    'OutputArguments', { ...
        engineOutputSchema(), ...
        engineOutputSchema(), ...
        engineOutputSchema(), ...
        fleetOutputSchema(), ...
        clusterOutputSchema(), ...
        countOutputSchema(), ...
        listOutputSchema(), ...
        countOutputSchema(), ...
        listOutputSchema(), ...
        listOutputSchema(), ...
        listOutputSchema(), ...
        listOutputSchema(), ...
        listOutputSchema(), ...
        engineOutputSchema()}, ...
    'QueryType', { ...
        "engine", ...
        "engine", ...
        "engine", ...
        "fleet", ...
        "clusters", ...
        "airborne_count", ...
        "airborne", ...
        "maintenance_count", ...
        "maintenance", ...
        "degrading", ...
        "critical", ...
        "early_failure", ...
        "top_risk", ...
        "highest_risk"});
end

function schema = engineInputSchema()
schema = struct( ...
    'engine_id', "string scalar or numeric scalar; engine identifier such as MW-105, Engine 105, or 105");
end

function schema = fleetInputSchema()
schema = struct( ...
    'engine_id', "string scalar; use fleet for fleet-wide queries");
end

function schema = topRiskInputSchema()
schema = struct( ...
    'engine_id', "string scalar; use fleet for fleet-wide queries", ...
    'max_results', "positive integer scalar or Inf; maximum number of ranked engine records to return");
end

function schema = engineOutputSchema()
schema = struct( ...
    'result', "struct scalar; includes engineID, faultClass, confidence percent, rul cycles, healthIndicator 0..1, opState, status, tickIndex, and snapshotPath");
end

function schema = fleetOutputSchema()
schema = struct( ...
    'result', "struct scalar; includes fleet bucket counts, operating-state counts, average health indicator, topRisk string array, tickIndex, and snapshotPath");
end

function schema = clusterOutputSchema()
schema = struct( ...
    'result', "struct scalar; includes HEALTHY, DEGRADING, CRITICAL, EARLY FAILURE, MAINT counts, operating-state counts, tickIndex, and snapshotPath");
end

function schema = countOutputSchema()
schema = struct( ...
    'result', "struct scalar; includes queryKind, opState, count, nTotal, operatingStates, tickIndex, and snapshotPath");
end

function schema = listOutputSchema()
schema = struct( ...
    'result', "struct scalar; includes queryKind, bucket or opState, count, nTotal, engines string array, engineRecords struct array, tickIndex, and snapshotPath");
end
